apiVersion: v1
kind: Service
metadata:
  name: litellm-api
  namespace: litellm-dev
spec:
  type: NodePort
  selector:
    app: litellm-api
  ports:
    - name: http
      port: 4000
      targetPort: 4000
      nodePort: 30080
