apiVersion: v1
kind: Service
metadata:
  name: ${service.name}
  namespace: ${namespace}
  labels:
    app: litellm-api
spec:
  type: ${service.type}
  ports:
  - port: ${service.port}
    targetPort: ${service.targetPort}
    protocol: TCP
    name: http
  selector:
    app: litellm-api
